### ISSUE TITLE
Add multi-layer feature

### ISSUE THREAD

**Issue by fire** [syoyo/tinyexr#53] opened 2017-12-17 18:43 UTC
How do you use multiple layers with this library?

**Comment by syoyo** [comment] 2017-12-18 05:10
Please describe an issue more precisely.

**Comment by fire** [comment] 2017-12-18 05:12
Given I have a exr with n layers, how would you access it from tinyexr?

[Test.zip](https://github.com/syoyo/tinyexr/files/1566686/Test.zip)

**Comment by fire** [comment] 2017-12-18 05:22
Example questions:

A) Require a list of the layers

B) Allow selection of different layers

C) Accessing the pixel info

**Comment by syoyo** [comment] 2017-12-18 05:25
OpenEXR specification does not support multilayer, it is stored in multichannel manner.
 You may iterate image channels using `EXRHeader.num_channels` and split channel name into layer string and channel string by `.` 

https://github.com/openexr/openexr/blob/develop/OpenEXR/IlmImf/ImfChannelList.h#L179
https://github.com/tiagoshibata/exrsplit

Contribution for the easy-access to multi-layers are always welcome!

**Comment by status-open-bounty** [comment] 2018-01-18 05:14
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xb5c179797cb522af9b43c26f5e82f231c8e7a033e66b1c295a60bd005e5c76ec](https://etherscan.io/tx/0xb5c179797cb522af9b43c26f5e82f231c8e7a033e66b1c295a60bd005e5c76ec)

**Comment by syoyo** [comment] 2018-01-18 05:26
I have assigned Bounty program to this issue.

Bounty hunter wanted!

Requirements : Load and parse multiple layers from channel string.

**Comment by arash009** [comment] 2018-04-25 05:02
@syoyo I've noticed this issue hasnt had any progress in some time, if you're happy, we'll put in some SNT as well to help increase the bounty value.

**Comment by syoyo** [comment] 2018-04-25 05:13
> @syoyo I've noticed this issue hasnt had any progress in some time, if you're happy, we'll put in some SNT as well to help increase the bounty value.

Cool! It would  be nice! How can we do it?

**Comment by arash009** [comment] 2018-04-25 10:07
We've added some SNT to the bounty as well now!

**Comment by syoyo** [comment] 2018-04-25 10:09
@arash009 Awesome!

**Comment by akien-mga** [comment] 2018-11-15 17:04
I'd suggest editing the issue title to be clearer, as it's not just about documenting things but adding a multilayer feature to TinyEXR to handle this out of the box (the documentation part for what's currently possible would be what is described in https://github.com/syoyo/tinyexr/issues/53#issuecomment-352329409).

**Comment by syoyo** [comment] 2018-11-15 17:08
> I'd suggest editing the issue title to be clearer,

I have fixed the title!

**Comment by fire** [comment] 2018-11-15 22:00
We discussed about two modes:

1. merge down all the [layers] using transparency
2. split into different images based on import

Merge down is harder but is needed by our implementation. Split is easier but requires ui on the implementation.

Comments?

**Comment by syoyo** [comment] 2018-11-19 12:41
> Split is easier but requires ui on the implementation.

PR for GUI for layer splitting would be appreciated. 
You may be interested in libui > https://github.com/andlabs/libui

**Comment by usakhelo** [comment] 2019-12-09 01:13
Hello @syoyo and @fire,
Is this issue still not resolved? I think I could look into fixing this.
I have few questions if it still makes sense:
1. Is implementing `void layers (&layerNames)` and others from `ImfChannelList.h` a way to fix this?
2. Should the default way of be taking rgba from first layer?
3. I also don't quite understand why merging is required, could explain a little please?
Thanks.

**Comment by fire** [comment] 2019-12-09 03:59
Imagine in a game engine, you have the ability to get an exr image.

What do you want to do with it?

You may want to get every single layer stacked and exported as one exr image. How do you do this with multiple layers?

You have multiple choices. 

1. Choose the the first layer
2. Merge down all the layers so that the transparency falls through all the layers
3. Choose one out of any number of layers.

This assume the engine only has the ability to have one output rgbafloat in the default configuration.

Channels is a different problem.

**Comment by usakhelo** [comment] 2019-12-09 05:00
I think I understand now.
I'm coming from CGI background and I've never seen exr layers merged because they usually carry very different information.
Would it make sense to implement just 1 and 3, without merging? Also, when choosing the layer you never know what and how many channels are there. It might be RGB, might be not. I think original `ImfChannelList.h` implementation makes sense, it just returns whatever there is.

And by default tinyexr can search for RGB channels in all the layers and return first one found.. That would keep it functional with normal and multilayer exr-s.

**Comment by usakhelo** [comment] 2019-12-09 05:18
One more question: the issue is not only about loading multi-layer images but also about producing them right? Is it possible to produce multi-layer images with tinyexr right now? I thought it might be possible because layers are just channel naming...

Thanks for the explanation @fire

**Comment by fire** [comment] 2019-12-09 05:24
This was the original use cases.

This is the photoshop use case.

I have different layers in a doument and I want to name them differently but composite them together.

This is the CGI usecase.

I have 4 PBR materials for a 3d mesh.

The first layer is RGBA for the albedo.
The second layer is RGB for ORM (Oculusion, Roughness and Metalness) 
The third layer is NORMAL maps.

So this image would contain all the textures for one material.

**Comment by syoyo** [comment] 2019-12-09 05:27
>  Is it possible to produce multi-layer images with tinyexr right now?

@usakhelo 

multi-layer is already supported and you can access channels if you use `ParseEXRHeaderFromFile` and `LoadEXRImageFromFile`

https://github.com/syoyo/tinyexr/blob/master/tinyexr.h#L11370

I think it would be better to implement `ImfChannelList.h` equivalent API(e.g. ChannelListIterator?) on top of it.

More better solution may be adding  OpenEXR compatible API > https://github.com/syoyo/tinyexr/issues/120

Merging layers would not be an task of TinyEXR.

**Comment by usakhelo** [comment] 2019-12-09 05:45
Thanks @syoyo and @fire,
I need some time to think and I'll be back with more questions.

**Comment by usakhelo** [comment] 2019-12-15 05:37
Hello,
I've made PR with a version of multi-layer support. It's more like minimal version than what `ImfChannelList.h` provides. I wanted to see if it's the right functionality and get the feedback from you.

**Comment by syoyo** [comment] 2019-12-16 07:02
@usakhelo Awesome! merged PR!

**Closed by syoyo** 2019-12-16 07:02 UTC
Labels: bounty, enhancement, help wanted

**Comment by syoyo** [comment] 2019-12-16 07:03
@usakhelo so you are eligible to receive 0.05 ETH as a bounty. Do you have ETH address?

**Comment by usakhelo** [comment] 2019-12-16 11:06
Thanks for fixing the leaks and merging @syoyo !
I don't have ETH address. May be I'll create one.
